### ISSUE TITLE
Partial Exclusions as a method 

### ISSUE THREAD

**Issue by alopez04** [NREL/reVX#148]
**Why this feature is necessary:**
PV setbacks are typically smaller than the reV resolution of 90-meters. We need a method to not overestimate the amount of land that would be excluded from say a 20-meter road setback. 

**A possible solution is:**
@mikebannis has created methods to capture partial exclusions that we should explore integrating into the setbacks codebase. 

**I have considered the following alternatives:**
Having Mike do it one layer at a time. 

**Additional context**
n/a

**Charge code**
WEPG.10348.08.01.06

**Urgency / Timeframe**
Not Urgent / July 2022

**Comment by grantbuster** [comment]
@mikebannis and/or @alopez04 can you expand on the method you want to have implemented? @ppinchuk are you already working on this / do you already know the details of what they want?

**Comment by ppinchuk** [comment]
@grantbuster Yea Anthony has mentioned this to me ahead of time. I should be able to handle this and #146, unless you tell me otherwise!

**Comment by grantbuster** [comment]
That would be great, was just trying to get an idea of what you already knew about vs what we need more details on.
