### ISSUE TITLE
Improve profile definition for trans routing layer generation

### ISSUE THREAD

**Issue by mikebannis** [NREL/reVX#206]
Generating transmission routing costs/friction/barrier layers currently requires specifying a template raster and an existing H5 file. Both of which must share the same shape, CRS, and transform.  Ideally only one or the other would be required. 

Note: Previous experiments with generating the lat and long points for the H5 meta data resulted in lats and longs that differed slightly from from the existing meta data (e.g., 39.123 vs 39.124) and had a large number of "inf".

**Comment by ppinchuk** [comment]
Tried reproducing, but couldn't. If we come across this again, let's open a reproducing issue then.
