### ISSUE TITLE
JSON config files not included when package is pip installed

### ISSUE THREAD

**Issue by mjgleason** [NREL/reVX#215]
**Bug Description**
When pip installing from git (e.g., `pip install nrel-reVX@git+ssh://git@github.com/NREL/reVX@v0.3.54`), the json configuration files needed by the `add-reeds-cols` are not included in the installation. 

**Full Traceback**
Users will see an error like:
```python
  File "envs/rev/lib/python3.10/site-packages/reVX/utilities/reeds_cols.py", line 229, in add_reeds_columns
    sc = add_nrel_regions(sc)
  File "envs/rev/lib/python3.10/site-packages/reVX/utilities/reeds_cols.py", line 88, in add_nrel_regions
    with open(os.path.join(CONFIG_DIR, "nrel_regions.json")) as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'envs/rev/lib/python3.10/site-packages/reVX/utilities/config/nrel_regions.json'
```

**Additional context**
The files that are missing are the json files found in `reVX/utilities/config`. This should be fixable by adding the `package_data` parameter to `setup` call in `setup.py`, something like : `package_data={"": ["**/*.json"]}` (note: this may not be exactly right).

This error will not occur if you `git clone` the repo and install with `pip install .` because the files needed will be in the local repo. It only occurs if you pip install the package directly.

**Comment by ppinchuk** [comment]
Weirdly this now works if you pip install from a commit but not from a release... 

Probably related to some distribution packaging done when creating the release. Needs further investigation

**Comment by ppinchuk** [comment]
Seems to work ok with 0.3.57

Let me know if this is still an issue for you
