### ISSUE TITLE
Test reVX pipeline for ReEDS technologies

### ISSUE THREAD

**Issue by mmowers** [NREL/reVX#43]
**Why this feature is necessary:**
To make sure reVX is running and producing outputs for all ReEDS technology types: onshore wind, offshore wind, urban PV, and rural PV.

I am providing onshore and offshore wind config files now. I will attach urban and rural PV config files later this week.
[wind.zip](https://github.com/NREL/reVX/files/4247200/wind.zip)

**Charge code**
WEPG.10348.08.01.02

**Urgency / Timeframe**
Onshore wind: Monday, 2020-03-02
Offshore wind: Monday, 2020-03-02, dependent on https://github.com/NREL/reV/issues/124
Urban PV: TBD
Rural PV: TBD

**Comment by mmowers** [comment]
Thanks @MRossol! checking through some of the results now with Trieu etc

**Comment by MRossol** [comment]
@mmowers Urban PV runs are done:
/shared-projects/rev/projects/reeds_jan2020/urban_pv/output/

**Comment by MRossol** [comment]
Working on master
