### ISSUE TITLE
ReEDS onshore wind rep profiles include offshore sites

### ISSUE THREAD

**Issue by mmowers** [NREL/reVX#50]
**Bug Description**
Certain onshore wind representative profiles actually correspond to offshore sites.

**To Reproduce**
See the 'meta' table of /shared-projects/rev/projects/reeds_jan2020/wind/onshore_wind/output/windons_hourly_cf.h5. Note that the rep_gen_gids for region 1, class 4-7 are offshore sites.

**Expected behavior**
Offshore wind data is filtered out and not included in onshore wind representative profiles

**Screenshots**
![image](https://user-images.githubusercontent.com/3431592/76251730-ea23a680-621d-11ea-94a2-9ef41821e932.png)

**Comment by MRossol** [comment]
Fixed in #48 
There was a typo in the CLI that was not implementing the filter

**Comment by MRossol** [comment]
@mmowers  I've re-run the on and offshore wind runs. Can you check to see if this is fixed (and if so close)?

**Comment by mmowers** [comment]
Looks good! Representative profiles now are reflecting onshore sites. Closing this issue.
