### ISSUE TITLE
ReEDS representative profiles appear to not be in local time

### ISSUE THREAD

**Issue by mmowers** [NREL/reVX#51]
**Bug Description**
It appears that the representative profile outputs for ReEDS may not be shifted to local time (assuming the input profiles are in UTC).

**To Reproduce**
Compare the 'rep_profiles_0' tables of these two files:
- input:  /shared-projects/rev/projects/reeds_jan2020/wind/ reeds_wind_rep_profiles_2012.h5
- output: /shared-projects/rev/projects/reeds_jan2020/wind/onshore_wind/output/windons_hourly_cf.h5

Specifically, compare the profile for sc_id 2726 (column 2726) in the input table to its corresponding entry in the output table (it is the representative profile for region 1 class 8, or column 4 of the output table). The comparison looks like:
![image](https://user-images.githubusercontent.com/3431592/76255573-c31ca300-6224-11ea-856b-0b44b070d815.png)

Notice that, other than being scaled by 1000, the output has only shifted by -1 as compared to the input (correctly accounting for our requirement to start the arrays at 1am), while the timezone correction should be an additional shift of -8.

**Expected behavior**
Representative profiles are shifted to local time.

**Comment by MRossol** [comment]
We only made timeslices in local time, will re-implement that in profiles

**Comment by MRossol** [comment]
@mmowers This should also be fixed in the most recent runs on eagle (I've replaced the data in */output/).

Can you check and close this if it's fixed, waiting on @grantbuster  to approve the PR #52

**Comment by mmowers** [comment]
Hi @MRossol , I can't access the new output/ folder. could you open up permissions?

**Comment by mmowers** [comment]
Looks good now! I spot checked sc_id 2726 and a few others, and they have been shifted to local. Closing this issue.
