### ISSUE TITLE
Shadow flicker wind exclusions 

### ISSUE THREAD

**Issue by grantbuster** [NREL/reVX#70]
**Why this feature is necessary:**
Wind build regulations are limiting the amount of shadow flicker (hours per year) on households/residences/buildings. We have a shadow flicker model (from Darice) and need to think about how to use this to create an exclusions file for ingestion into reV. 

**A possible solution is:**
From discussion on 12/8/2020 we think the steps required are:
1. get 90m building/residences raster
2. run shadow flicker for ever SC point for one turbine technology (what kind of wind resource do we need? Wind speed AND direction? Just solar position?)
3. make a database of high res shadow flicker shapes dependent on geospatial info (solar and wind)
4. map high res shadow flicker database to 90m resolution
5. map 90m res shadown flicker to an exclusions file (iterate through buildings and "back out the exclusions" from that shadow)

**Charge code**
WEPG.10348.08.01.01

**Urgency / Timeframe**
?

**Comment by MRossol** [comment]
Inputs:
- lat
- lon
- blade_length (m)
- wind_dir (optional), degrees from N

Examples: 200 x 300m heat map

**Comment by grantbuster** [comment]
Here's a bad drawing of the desired exclusion mask. The turbine flicker shape should be computed on a 270x270m output array, which will be converted to a 3x3 array of annual flicker fraction or a boolean, and then we need to iterate through 90m pixels and exclude those that would shade/flicker a building. 

![image](https://user-images.githubusercontent.com/12700356/103557519-9222f400-4e70-11eb-8062-8b2f136d76b7.png)

**Comment by MRossol** [comment]
Plan:
- Run HOPP to produce a 270m x 270m heat map (3x3 90m array). Convert shadow profile into a boolean mask
- Compute i,j coordinates that would cause exclusion.
- Check if a building is in the above i,j vector
