### ISSUE TITLE
reVX prints wrong version

### ISSUE THREAD

**Issue by WilliamsTravis** [NREL/reVX#72]
**Bug Description**
Printing ```reVX.__version__``` results in "0.1.1", though it is clearly a more recent version because up-to-date functionality is available. This is also the case in the shared "modulefiles" environment. 

**Code Sample**
```python
import reVX

print(reVX.__version__)
```

**Expected behavior**
"0.3.8" is printed

**System (please complete the following information):**
 - OS:  Linux
 - Compute hardware: Eagle
 - Version: 0.3.8

**Comment by MRossol** [comment]
Implemented in #73
