### ISSUE TITLE
Add scale factor feature to the REDE technical potential module

### ISSUE THREAD

**Issue by EvanRosenliebNREL** [NREL/reVX#76]
**Why this feature is necessary:**
Many of the REDE rasters for the current tool are scaled for performance reasons. Without a scale factor option in the both the h5 creation tool and the technical potential tool, all rasters will need to be rescaled before porting which will increase time to transfer and additionally they will be more costly to store over the long run.

**A possible solution is:**
Add a feature to the code where we can add a scale factor attribute for a dataset, where it will then be scaled during the analysis portion -- like in other reV/reVX modules

**I have considered the following alternatives:**
Unscaling the rasters before transfering -- not ideal for reasons listed above. 

**Charge code**
WFED.11084.02.04.07

**Urgency / Timeframe**
Unfortunately, sort of urgent! We are in cruch time for transferring the REDE tool.

**Comment by EvanRosenliebNREL** [comment]
@MRossol As requested :-)

**Comment by MRossol** [comment]
implemented in #77
