### ISSUE TITLE
Plexos plant aggregator doesn't work for offshore wind (pre-NRWAL)

### ISSUE THREAD

**Issue by grantbuster** [NREL/reVX#91]
**Bug Description**
Plexos plant aggregator attempts to map capacity factor mean values to supply curve points via resource GID. This fails when run after the offshore aggregation. 

The failure line is here: https://github.com/NREL/reVX/blob/01dfce1aa83d5004caae44fbe69a8ed0035447bc/reVX/handlers/sc_points.py#L547

And it fails because the offshore SC point has all the original WTK resource GIDs that no longer map to the reV gen files that have been aggregated. 

![image](https://user-images.githubusercontent.com/12700356/109348542-e5427300-7831-11eb-967f-b361461a7a86.png)

Integration of NRWAL into reV should resolve this issue because there will be no weird handling of offshore points. I'm just starting this issue so we have a record.

**Comment by MRossol** [comment]
@grantbuster  Have you tried this post NRWAL?

**Comment by grantbuster** [comment]
No, i plan on only using the SimplePlantBuilder moving forward. The PlexosPlants utility is too complicated and brittle for the stuff I was working on. We should consider this resolved though, since there is no difference in onshore vs. offshore aggregation output format.
