### ISSUE TITLE
Least Cost Tranmission Tables

### ISSUE THREAD

**Issue by MRossol** [NREL/reVX#97]
Why this feature is necessary:
Update transmission table to compute non-linear distances using exclusion layers
Add a penalty to the paths in certain specifics

A possible solution is:
Build a reVX tool to build the transmission connection tables with custom exclusions layers and added costs
Allow parsing of a new scalar and/or multiplier column from the table when computing LCOT

Charge code
WEPG 10348 08.01.01

Urgency / Timeframe
Q2-Q3

**Comment by mikebannis** [comment]
Questions:

- Should cost paths be calculated from SC points or from x-mission points?
- If calculating path cost rasters, rasters need to be clipped down before running MCP_Geometric()
- Whats the clip radius? Dynamic?
- Calculating a full least cost raster seems somewhat unnecessary, as there’s a limited number of realistic x-mission points to tie into for a given SC. Can we just calculate the paths for those? There's also a fair chance that the cost to further points uses the calculated cost for closer points, so the "full" raster effectively has to be calculated.

**Comment by mikebannis** [comment]
Layers for calculating path costs:
- Land cover (trees, grass, etc)
- Slope raster
- Buildings?

**Comment by MRossol** [comment]
Cost layers:
- Right of Way (ROW): crop, urban, suburban
- Terrain: Wetlands, Forest, Mountain
- Slope
- ISO/BA

**Comment by MRossol** [comment]
Output tables for each combination below:
exclusions resolutions = 32, 64, 128
Line voltage =

**Comment by mikebannis** [comment]
### Work flow
1. **Prep**
  * Obtain rasters
    * ROW
    * Terrain
    * Slope
    * ISO/BA ???
    * Exclusions
  * Convert original rasters to multipliers
    * Use appropriate multipliers for each utility territory
  * Merge multiplier rasters into cost raster
    * One per capacity class/bin (100MW, 200MW, 400MW, 1GW) 
2. **Processing**
  * For each capacity class
    * For each SC point
      * Clip cost raster by distance
      * Calculate least cost path raster from clipped cost raster
      * Determine least cost path for each x-mission feature within least cost path raster
        * Substations 
        * Load centers
        * X-mission lines
        * Sinks
      * Add appropriate connection costs for possible connection
        * New substation $
        * Connection to existing SS $
        * Is there a cost for connecting to load centers/sinks?
      * Add each connection to table
        * Cost of connection
        * Distance
        * Path? 
        
      *

**Comment by MRossol** [comment]
Build cost rasters based on:
- ISO region which determines multipliers
- Right of way (ROW)
- Terrain
- Line size (capacity)

Compute least-cost path:
- total cost
- distance

Apply line distance multiplier based on above distance

**Comment by MRossol** [comment]
Rehash of todays meeting:
Steps:
NOTE: These need to be run independently for each kV bin provided by OWEN:
1) Create cost array for each kV bin
-  create cost raster using basic tie-line costs * ROW or terrain multipliers all of which vary by ISO
- Exclude protected areas by setting to -1
2) Compute cost and distance to connect EACH sc_point to `n` nearest transmission features
NOTE: this should be dynamic, you give the code the sc `resolution` and it runs all possible sc_points, again this is for a SINGLE kV bin so the transmission features need to be filtered to JUST those in the proper kV bin
- find clipping distance as the maximum distance from `sc_point` to nearest `infinite_sink` OR `sc_point` to `n` nearest (`substations`, `load_centers`, `sinks`)
- clip cost array around `sc_point` to distance computed above
- Run MCP_Geometric.find_cost(`sc_point_idx`) to compute the least-cost path from the sc_point to ALL pixels in the clipped cost array
- For all transmission features in clipped cost array and:
   - Compute connection cost as `least_cost from MCP + connection cost`
   - distance using the least-cost path `traceback` from MCP
   - NOTE: for transmission lines: extract all array pixels transversed by line and find the least cost value, this will be the connection location and will be used to compute the above values.
- Repeat for all sc_points

**Comment by mikebannis** [comment]
![image](https://user-images.githubusercontent.com/18619942/114918293-2859a500-9de4-11eb-95e4-37515271bf80.png)
Possible issue: Least cost paths can only go 8 directions between raster cells. In areas of consistent costs, this can result in exaggerated path lengths as shown in the image. White lines are the least cost paths, the dashed red line is the direct path. This appears to be less of an issue for areas with variable costs.

**Comment by mikebannis** [comment]
![image](https://user-images.githubusercontent.com/18619942/114918619-8090a700-9de4-11eb-9415-c003d4ea6048.png)
At some locations, the nearest point on a t-line to a supply curve point is coincident with a substation. For example, the red star is the SC point. The closest substation is the white/cyan dot at encampment. The closest t-line is the Trowbridge to Encampment 35kV line, and the closest point on that line to the SC is identical to the location of the encampment substation. The least cost path to both the t-line and the substation are identical, so adding both costs/paths to the Possible Connections Table seems excessive, if connecting to the substation is always cheaper between the two options.

**Comment by mikebannis** [comment]
![image](https://user-images.githubusercontent.com/18619942/114918873-d402f500-9de4-11eb-923f-86c94d1e7538.png)
Water bodies currently have a cost multiplier of 1, which is unrealistic. Additionally, while transmission lines can cross smaller water bodies, and towers can be build in shallow water, building towers in deep water is unrealistic. Inland bathymetry datasets are very limited in CONUS. 

A preprocessing step could be used to determine areas that are wide enough to require a tower and then block the areas that need towers.  If towers can be a maximum of 1000m apart, simply shrinking all water bodies by 500m would create the no-tower zone in the center of lakes that are wider than 1km. This would also get rid of any lakes that are small enough to ignore from the calcs.

The green polygon is the original NHD waterbody, clearly not measured at full-pool conditions. The red polygon is the reverse buffered no-tower zone, so t-lines would be allowed to cut across the green portion of the lake if that’s the lowest cost path, but would be prevented from crossing the red zone.

**Comment by mikebannis** [comment]
A system needs to be determined for excluding trans features outside of CONUS. I'm already excluding anything outside of the reV raster template, but the layers going into the multiplier have a smaller footprint than then template raster.

Small red dots are supply curve points. Purple indicates a multiplier of 1.
![image](https://user-images.githubusercontent.com/18619942/114946821-27873a00-9e09-11eb-96bf-58bcfcd910dd.png)
![image](https://user-images.githubusercontent.com/18619942/114946849-340b9280-9e09-11eb-97af-96ec3941ea98.png)

**Comment by mikebannis** [comment]
![image](https://user-images.githubusercontent.com/18619942/119177111-15607300-ba29-11eb-819e-7145e7988bdc.png)

**Comment by MRossol** [comment]
Island issue thoughts:
1) Use something like this to place sc_point center post-exclusions:
https://github.com/NREL/reVX/blob/f9ac3fe86e4a274e5427d6a06cce693151aafc4c/reVX/offshore/offshore_inputs.py#L255-L312

2) Dealing with transmission islands:
    a) use `-1` values in the cost array to find sc_points that cannot be attached to transmission (`force=False`)
    b) If `force=True` change `-1` to a large value (`10e9`) to force connections directly across "moats", then during the distance calculation process (path tracing), count up the number of `10e9` pixels and replace them with a "moat" cost, update total cost value.

**Comment by mikebannis** [comment]
![image](https://user-images.githubusercontent.com/18619942/121410597-fd8d5800-c91f-11eb-95c1-fc8d8b45da1e.png)

**Comment by MRossol** [comment]
transmission_table columns:
Rename current columns:
sc_id: sc_point_gid
trans_id: trans_gid
trans_type: category # Also please use the values under category in the source table (i.e., TransLine, Substation, PCALoadCen, LoadCen
lenght: dist_km
adj_line_cost: tie_line_cost | line_cost # I'm assuming this is the tie-line cost...
total_cost: lcot

Missing columns:
ac_cap # take from the source table
trans_line_gids # these are the transmission lines that connect to the given feature, only needed for Substations
connection_cost # I think this is the sum of `xformer_cost`, `sub_upgrade_cost`, and `new_sub_cost`?
sc_point_row_id # While redundant IF sc_point_gids are created the same way, it is a useful test to make sure that is true...
sc_point_col_id # See above

**Comment by MRossol** [comment]
NOTES on refactor needs:
1) Source cost/exclusions layers from a .h5 file instead of .tiffs
2) remove reference to sc_table and replace with resolution. Use exclusion extent and resolution to generate deterministic set of sc_points
3) Use either exclusion layer or tech-map(s) to determine valid sc_points to connect to
4) Compute costs for all lines attached to each sub-station (????)

**Comment by mikebannis** [comment]
Regarding 4, the current process connects to the 10 nearest substations and 10 nearest t-lines, for 20 total, which includes some duplicate connection sites. It would be better to connect to a total of the 10 nearest substations and t-lines. Ideally, reV would have a table of existing transmission lines and use that to determine substation capacity which would significantly reduce the size of the tie-line cost tables at the expense of slightly more complicated logic within reV.

**Comment by MRossol** [comment]
That could work, but begs the question, why are we only "allowing" connection to 10 of `n` t-lines? It seems like the most robust approach would be to connect to the 10 nearest substations/load-centers/sinks + all t-lines connected to any sub-stations.

**Comment by MRossol** [comment]
I also think we shouldn't worry about size, if these .csvs are to big we can move to .json, drop columns, change dtype or use .h5.

**Comment by mikebannis** [comment]
The csv files are getting big enough that Excel is having issues with them, which is making QAQC of the predicted tie-line costs a little challenging. There are ways around that.

Proposed work flow, assuming we want the 10 nearest features. 

- Calculate distances from SC point to substations and lines
- Grab 10 nearest features (either subs or lines)
- For each subs, grab all connected t-lines if not already in grab bag
- Include one load center and one sink in grab bag
- Calculate paths and costs to all features in grab bag

Downside of the above work flow is significant redundancy in extra connections to transmission lines above the needed 10. For 100MW it increases the cost table size and computation time by ~60%, for 1000MW it increases the cost table by 200%.

On the upside there are no more huge costs to discourage connections other than for the sinks and no need to use "don't connect" flags in reV for some features.

**Comment by MRossol** [comment]
Why are we doing QA/QC in excel... I really don't think excel performance should be a priority for a python model. I suggest for the least-cost path tables we move to .h5 and have each table be a dataset. That way we can more closely control the dtypes to reduce data size. We could also drop a lot of the columns used for de-bugging.

**Comment by mikebannis** [comment]
Execl is easy and I thought Owen was using it, turns out he's using Tableau. But, agreed, and using an h5 file would dramatically reduce the file size.

**Comment by MRossol** [comment]
produced using #131
